version = 0.1

[default.deploy.parameters]
stack_name = "cs-copilot-backend"
resolve_s3 = true
s3_prefix = "cs-copilot-backend"
profile = "cs-copilot"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "StageName=\"dev\" AllowedOrigin=\"http://localhost:3000\" HmacSecretString=\"a53d5ef937a206184885fbe57dba2ae3efd70cc1d9475d53b7dc8cd08a00c1c4\" DataBucket=\"barcai-cs-success-copilot\""
image_repositories = []

[default.global.parameters]
region = "ap-southeast-1"
